### PR TITLE
Full API refactor

### PR DESCRIPTION
**Pull request by evannorstrand-mp**
First off, I want to acknowledge that this is a pretty massive refactoring of basically all of tangent. 

Changelog:

1. I've renamed the folder structure to better match the functionality contained. 
2. I refactored the single file api into a properly organized API.
3. I've fixed numerous bugs, it would hours to type up every fix.
4. I fixed a handful of UI bugs, I am still working through these changes.

I've done quite a bit of manual testing, and my refactor doesn't seem to have broken tangent in any noticeable way.

### CODE REVIEW

**Comment by itsPreto** [comment]
This looks great dude, wow! I'll do some testing later today but from just glancing at it I'd be okay merging this. 

Bug kudos!

**Comment by evannorstrand-mp** [comment]
I have found quite a few UI bugs. I'll be working on fixing those and converting from JSX to TSX.

Once the UI is done, I'll add in OpenAI compatibility in a 3rd PR.

**Comment by LatchyCat** [comment]
LGTM

**Comment by itsPreto** [comment]
Most of the functionality was working as expected except for the data processing part-- when trying to import my archived chat data from either chatgpt or claude I was seeing this error:

```
Error processing single month: pdist(): argument 'input' (position 1) must be Tensor, not numpy.ndarray
Processing month 2023-09 with 71 chats...
Starting processing for month 2023-09 with 71 chats
Fetching embeddings for 71 titles...
Embeddings retrieved successfully.
Performing UMAP...
....
....
....
Error processing single month: pdist(): argument 'input' (position 1) must be Tensor, not numpy.ndarray
Processing month 2023-10 with 99 chats...
Starting processing for month 2023-10 with 99 chats
Fetching embeddings for 99 titles...
Incoming request:
Path: /api/process/status/1734645437.7325509
Method: GET
```


after poking around and tweaking it a bit I got it all working again-- both the graph and the topics list show up on the left-hand panel. here is the diff if you want to update this PR:

```diff
diff --git a/tangent-api/requirements.txt b/tangent-api/requirements.txt
index 273b072..3dc7b47 100644
--- a/tangent-api/requirements.txt
+++ b/tangent-api/requirements.txt
@@ -1,5 +1,6 @@
 Flask
 flask-cors
+torch
 numpy
 pandas
 scipy
diff --git a/tangent-api/src/services/clustering.py b/tangent-api/src/services/clustering.py
index 3de4501..78bacec 100644
--- a/tangent-api/src/services/clustering.py
+++ b/tangent-api/src/services/clustering.py
@@ -1,5 +1,6 @@
 import os
 import hdbscan
+from scipy.spatial.distance import pdist, squareform
 import numpy as np
 from services.topic_generation import generate_topic_for_cluster
 from sklearn.base import defaultdict
diff --git a/tangent-api/src/services/data_processing.py b/tangent-api/src/services/data_processing.py
index 84ba2b0..18a218d 100644
--- a/tangent-api/src/services/data_processing.py
+++ b/tangent-api/src/services/data_processing.py
@@ -3,9 +3,8 @@ import os
 import traceback
 import numpy as np
 import pandas as pd
-from collections import defaultdict
-
-from torch import pdist
+from collections import defaultdict 
+from scipy.spatial.distance import pdist, squareform 
 import umap
 from config import CLAUDE_DATA_DIR, CHATGPT_DATA_DIR
 from typing import List, Tuple
@@ -340,36 +339,33 @@ def process_single_month(chat_titles, month):
 
         embeddings_array = np.array(embeddings)
 
-        # Perform t-SNE
+        # Perform UMAP
         print("Performing UMAP...")
         reducer = umap.UMAP(n_neighbors=15, min_dist=0.1, random_state=42)
-
         embeddings_2d = reducer.fit_transform(embeddings_array)
-        # Calculate distances and perform clustering
-        distances = pdist(embeddings_array, metric="cosine")
+
+        # Calculate distances using scipy
+        distances = pdist(embeddings_array, metric='cosine')
         distance_matrix = squareform(distances)
 
         clusters = perform_clustering(distance_matrix, len(chat_titles))
 
         # Generate topics and metadata
         cluster_metadata = generate_cluster_metadata(
-            clusters, chat_titles, distance_matrix
-        )
+            clusters, chat_titles, distance_matrix)
 
         return {
-            "month_year": month,
-            "points": embeddings_2d.tolist(),
-            "clusters": clusters.tolist(),
-            "titles": chat_titles,
-            "topics": cluster_metadata,
-            "total_conversations": len(chat_titles),
+            'month_year': month,
+            'points': embeddings_2d.tolist(),
+            'clusters': clusters.tolist(),
+            'titles': chat_titles,
+            'topics': cluster_metadata,
+            'total_conversations': len(chat_titles)
         }
 
     except Exception as e:
         print(f"Error processing single month: {str(e)}")
         return None
-
-
 def analyze_branches(messages):
     """
     Enhanced branch detection that specifically looks for edited message branches
diff --git a/tangent-ui/src/components/layout/IntegratedDashboard.jsx b/tangent-ui/src/components/layout/IntegratedDashboard.jsx
index 9201a62..c48b391 100644
--- a/tangent-ui/src/components/layout/IntegratedDashboard.jsx
+++ b/tangent-ui/src/components/layout/IntegratedDashboard.jsx
@@ -40,11 +40,9 @@ const SharedHeader = ({
 }) => {
   return (
     <header
-      className={`${
-        isPanelCollapsed ? "w-screen" : "w-[80vw]"
-      } h-16 bg-background border border-border ${
-        isPanelCollapsed ? "left-0" : "left-[20vw]"
-      } z-[100] flex items-center px-6 transition-all duration-300`}
+      className={`${isPanelCollapsed ? "w-screen" : "w-[80vw]"
+        } h-16 bg-background border border-border ${isPanelCollapsed ? "left-0" : "left-[20vw]"
+        } z-[100] flex items-center px-6 transition-all duration-300`}
     >
       <Button
         variant="outline"
@@ -155,6 +153,7 @@ export const IntegratedDashboard = () => {
   const [isPulling, setIsPulling] = useState(false);
   const [pullStatus, setPullStatus] = useState("");
   const [detailedView, setDetailedView] = useState(false);
+  const [data, setData] = useState(null);
 
   const [nodes, setNodes] = useState([
     {
@@ -173,7 +172,6 @@ export const IntegratedDashboard = () => {
   // Add these state declarations at the top with other states
   const [sortBy, setSortBy] = useState("relevance");
   const [selectedCluster, setSelectedCluster] = useState(null);
-  const [data, setData] = useState(null);
 
   // Add this function with other handlers
   const handleTopicSelect = (clusterId) => {
@@ -373,36 +371,40 @@ export const IntegratedDashboard = () => {
     return () => window.removeEventListener("keydown", handleKeyDown);
   }, [handleSave]);
 
+
   useEffect(() => {
     const fetchData = async () => {
       try {
         const response = await fetch("http://127.0.0.1:5001/api/visualization");
         const responseData = await response.json();
-        const chatsWithReflections = new Set(
-          responseData.chats_with_reflections
-        );
-
-        if (responseData.length > 0) {
-          const chartData = [
-            {
-              id: "points",
-              data: responseData.points.map((point, i) => ({
-                x: point[0],
-                y: point[1],
-                cluster: responseData.clusters[i],
-                title: responseData.titles[i],
-                hasReflection: chatsWithReflections.has(responseData.titles[i]),
-              })),
-            },
-          ];
-
-          setData({
-            chartData,
-            topics: responseData.topics,
-          });
+        console.log("API Response:", responseData); // Debug log
+
+        if (!responseData.points || !responseData.clusters || !responseData.titles) {
+          console.warn("Missing required data fields");
+          return;
         }
+
+        const chatsWithReflections = new Set(responseData.chats_with_reflections || []);
+
+        // Transform data into the format TopicsPanel expects
+        const formattedData = {
+          chartData: [{
+            id: "points",
+            data: responseData.points.map((point, i) => ({
+              x: point[0],
+              y: point[1],
+              cluster: responseData.clusters[i],
+              title: responseData.titles[i],
+              hasReflection: chatsWithReflections.has(responseData.titles[i]),
+            })),
+          }],
+          topics: responseData.topics || {}
+        };
+
+        console.log("Formatted data for TopicsPanel:", formattedData); // Debug log
+        setData(formattedData);
       } catch (error) {
-        console.error("Error fetching data:", error);
+        console.error('Error fetching data:', error);
       }
     };
 
@@ -596,9 +598,8 @@ export const IntegratedDashboard = () => {
 
       {/* Right Content Area */}
       <div
-        className={`${
-          isPanelCollapsed ? "w-full" : "ml-[20vw] w-[80vw]"
-        } flex flex-col transition-all duration-300`}
+        className={`${isPanelCollapsed ? "w-full" : "ml-[20vw] w-[80vw]"
+          } flex flex-col transition-all duration-300`}
       >
         <SharedHeader
           handleRefresh={handleRefresh}
diff --git a/tangent-ui/src/components/visualization/MainDashboard.jsx b/tangent-ui/src/components/visualization/MainDashboard.jsx
index 2e87732..26d5d67 100644
--- a/tangent-ui/src/components/visualization/MainDashboard.jsx
+++ b/tangent-ui/src/components/visualization/MainDashboard.jsx
@@ -5,22 +5,14 @@ import React, {
     useState,
     useRef,
     useCallback,
-    useContext,
 } from "react";
-import { Search, ZoomIn, ZoomOut, RefreshCw } from 'lucide-react';
 import { debounce } from 'lodash';
 
 // Updated component imports with new paths
 import ReflectionDialog from '../feedback/ReflectionDialog';
 import VisualizationPanel from '../visualization/VisualizationPanel';
-import TopicsPanel from '../visualization/TopicsPanel';
 import HoverTooltip from '../feedback/HoverTooltip';
 
-// Updated UI component imports
-import { Card, CardHeader, CardTitle, CardContent } from '../core/card';
-import { Input } from '../core/input';
-
-
 // Utility function for getting colors (moved outside component)
 function getColor(index) {
     const colors = [
diff --git a/tangent-ui/src/components/visualization/TopicsPanel.jsx b/tangent-ui/src/components/visualization/TopicsPanel.jsx
index dbb7a8f..9329240 100644
--- a/tangent-ui/src/components/visualization/TopicsPanel.jsx
+++ b/tangent-ui/src/components/visualization/TopicsPanel.jsx
@@ -1,4 +1,4 @@
-import React, { useState, useMemo } from 'react';
+import React, { useState, useMemo, useEffect } from 'react';
 // Core UI components
 import { Card, CardHeader, CardTitle } from '../core/card';
 import { ScrollArea } from '../core/scroll-area';
@@ -65,7 +65,7 @@ const TopicCard = ({
               >
                 {topicData.topic}
               </button>
-              
+
               {isActive && conversations.length > 0 && (
                 <button
                   onClick={(e) => {
@@ -201,6 +201,13 @@ const TopicsPanel = ({
     return counts;
   }, [data]);
 
+  // In TopicsPanel, add this near the top of the component:
+  useEffect(() => {
+    console.log("TopicsPanel received data:", data);
+    console.log("Topics:", data?.topics);
+    console.log("ChartData:", data?.chartData);
+  }, [data]);
+
   const filteredAndSortedTopics = useMemo(() => {
     if (!data?.topics) return [];
 
@@ -332,7 +339,11 @@ const TopicsPanel = ({
             ))
           ) : (
             <div className="p-8 text-center text-muted-foreground">
-              No topics match your criteria
+              {data?.topics ? (
+                'No topics match your criteria'
+              ) : (
+                'No topic data available. Please ensure data is loaded correctly.'
+              )}
             </div>
           )}
         </div>
```

**Comment by itsPreto** [comment]
Actually, I'll just merge this and push a small follow-up PR with the tweaks.

**Pull request merged**
